version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://kitchen_user:kitchen_pass@db:5432/kitchen_db

  db:
    image: postgres:15
    container_name: pg_2kitchen
    restart: always
    environment:
      POSTGRES_USER: kitchen_user
      POSTGRES_PASSWORD: kitchen_pass
      POSTGRES_DB: kitchen_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg_data:
