services:
  - type: web
    name: 2kitchen-backend
    env: go
    region: oregon
    plan: starter
    buildCommand: go build -o main ./cmd/server
    startCommand: ./main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: 2kitchen-db
          property: connectionString

databases:
  - name: 2kitchen-db
    engine: postgres
    plan: starter
    region: oregon
